version: '3.10'

services:
  ci-precommit:
    build:
      context: .
      dockerfile: tests/Dockerfile.precommit
    volumes:
    - .:/app
    working_dir: /app
    entrypoint: 'pre-commit run --all-files --verbose'

  ci-pytest:
    build:
      context: .
      dockerfile: tests/Dockerfile.pytest
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: 'pytest -s ./tests/'