name: Validate

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "main", "master" ]
    # paths-ignore:
    #   - "**/*.md"
    #   - "**/*.rdf"
    #   - "**/*.jsonld"
  pull_request:
    branches: [ "main", "master"]
    # paths-ignore:
    #   - "**/*.md"
    #   - "**/*.rdf"
    #   - "**/*.jsonld"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Run a script
        run: |-
          pip install pre-commit
          pre-commit run --all-files --verbose
jobs:
  test-url:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pytest
    - name: Run tests
      run: pytest -s ./tests/test_urls.py
